# Generated by Django 5.2.8 on 2026-02-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='categorie',
            field=models.CharField(choices=[('reseaux', 'Réseaux informatique'), ('cuniculture', 'Cuniculture')], default='reseaux', max_length=20),
        ),
    ]
