# Generated by Django 5.2.8 on 2026-02-09 13:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articles_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='contenu',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
