# Generated by Django 5.2.8 on 2026-02-09 15:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articles_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='contenu',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
